// <auto-generated />
namespace Repository.Mysql.FootballDBMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class InitiateFootballDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitiateFootballDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202008101047066_InitiateFootballDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
