//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pose_sports_statistics.Pages
{


	public partial class InterestedEvent
	{

		/// <summary>
		/// ctrl_interestedEventList control.
		/// </summary>
		/// <remarks>
		/// Auto-generated field.
		/// To modify move field declaration from designer file to code-behind file.
		/// </remarks>
		protected global::Pose_sports_statistics.Controls.InterestedEventList ctrl_interestedEventList;
	}
}
