//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoseWebService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="O_Hello", Namespace="http://schemas.datacontract.org/2004/07/PosePacket.HelloWorld")]
    public partial class O_Hello : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PoseWebService.Auth")]
    public interface Auth
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Auth/P_GetCredentials", ReplyAction="http://tempuri.org/Auth/P_GetCredentialsResponse")]
        byte[] P_GetCredentials(string i_name);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Auth/P_GetCredentials", ReplyAction="http://tempuri.org/Auth/P_GetCredentialsResponse")]
        System.IAsyncResult BeginP_GetCredentials(string i_name, System.AsyncCallback callback, object asyncState);
        
        byte[] EndP_GetCredentials(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthChannel : PoseWebService.Auth, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class P_GetCredentialsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public P_GetCredentialsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public byte[] Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthClient : System.ServiceModel.ClientBase<PoseWebService.Auth>, PoseWebService.Auth
    {
        
        private BeginOperationDelegate onBeginP_GetCredentialsDelegate;
        
        private EndOperationDelegate onEndP_GetCredentialsDelegate;
        
        private System.Threading.SendOrPostCallback onP_GetCredentialsCompletedDelegate;
        
        public AuthClient()
        {
        }
        
        public AuthClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public AuthClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AuthClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AuthClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public event System.EventHandler<P_GetCredentialsCompletedEventArgs> P_GetCredentialsCompleted;
        
        public byte[] P_GetCredentials(string i_name)
        {
            return base.Channel.P_GetCredentials(i_name);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginP_GetCredentials(string i_name, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginP_GetCredentials(i_name, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public byte[] EndP_GetCredentials(System.IAsyncResult result)
        {
            return base.Channel.EndP_GetCredentials(result);
        }
        
        private System.IAsyncResult OnBeginP_GetCredentials(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            string i_name = ((string)(inValues[0]));
            return this.BeginP_GetCredentials(i_name, callback, asyncState);
        }
        
        private object[] OnEndP_GetCredentials(System.IAsyncResult result)
        {
            byte[] retVal = this.EndP_GetCredentials(result);
            return new object[] {
                    retVal};
        }
        
        private void OnP_GetCredentialsCompleted(object state)
        {
            if ((this.P_GetCredentialsCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.P_GetCredentialsCompleted(this, new P_GetCredentialsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void P_GetCredentialsAsync(string i_name)
        {
            this.P_GetCredentialsAsync(i_name, null);
        }
        
        public void P_GetCredentialsAsync(string i_name, object userState)
        {
            if ((this.onBeginP_GetCredentialsDelegate == null))
            {
                this.onBeginP_GetCredentialsDelegate = new BeginOperationDelegate(this.OnBeginP_GetCredentials);
            }
            if ((this.onEndP_GetCredentialsDelegate == null))
            {
                this.onEndP_GetCredentialsDelegate = new EndOperationDelegate(this.OnEndP_GetCredentials);
            }
            if ((this.onP_GetCredentialsCompletedDelegate == null))
            {
                this.onP_GetCredentialsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnP_GetCredentialsCompleted);
            }
            base.InvokeAsync(this.onBeginP_GetCredentialsDelegate, new object[] {
                        i_name}, this.onEndP_GetCredentialsDelegate, this.onP_GetCredentialsCompletedDelegate, userState);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PoseWebService.HelloWorld")]
    public interface HelloWorld
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld/P_Hello", ReplyAction="http://tempuri.org/HelloWorld/P_HelloResponse")]
        PoseWebService.O_Hello P_Hello(string input);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/HelloWorld/P_Hello", ReplyAction="http://tempuri.org/HelloWorld/P_HelloResponse")]
        System.IAsyncResult BeginP_Hello(string input, System.AsyncCallback callback, object asyncState);
        
        PoseWebService.O_Hello EndP_Hello(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWorldChannel : PoseWebService.HelloWorld, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class P_HelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public P_HelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public PoseWebService.O_Hello Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((PoseWebService.O_Hello)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldClient : System.ServiceModel.ClientBase<PoseWebService.HelloWorld>, PoseWebService.HelloWorld
    {
        
        private BeginOperationDelegate onBeginP_HelloDelegate;
        
        private EndOperationDelegate onEndP_HelloDelegate;
        
        private System.Threading.SendOrPostCallback onP_HelloCompletedDelegate;
        
        public HelloWorldClient()
        {
        }
        
        public HelloWorldClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public HelloWorldClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HelloWorldClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HelloWorldClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public event System.EventHandler<P_HelloCompletedEventArgs> P_HelloCompleted;
        
        public PoseWebService.O_Hello P_Hello(string input)
        {
            return base.Channel.P_Hello(input);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginP_Hello(string input, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginP_Hello(input, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public PoseWebService.O_Hello EndP_Hello(System.IAsyncResult result)
        {
            return base.Channel.EndP_Hello(result);
        }
        
        private System.IAsyncResult OnBeginP_Hello(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            string input = ((string)(inValues[0]));
            return this.BeginP_Hello(input, callback, asyncState);
        }
        
        private object[] OnEndP_Hello(System.IAsyncResult result)
        {
            PoseWebService.O_Hello retVal = this.EndP_Hello(result);
            return new object[] {
                    retVal};
        }
        
        private void OnP_HelloCompleted(object state)
        {
            if ((this.P_HelloCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.P_HelloCompleted(this, new P_HelloCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void P_HelloAsync(string input)
        {
            this.P_HelloAsync(input, null);
        }
        
        public void P_HelloAsync(string input, object userState)
        {
            if ((this.onBeginP_HelloDelegate == null))
            {
                this.onBeginP_HelloDelegate = new BeginOperationDelegate(this.OnBeginP_Hello);
            }
            if ((this.onEndP_HelloDelegate == null))
            {
                this.onEndP_HelloDelegate = new EndOperationDelegate(this.OnEndP_Hello);
            }
            if ((this.onP_HelloCompletedDelegate == null))
            {
                this.onP_HelloCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnP_HelloCompleted);
            }
            base.InvokeAsync(this.onBeginP_HelloDelegate, new object[] {
                        input}, this.onEndP_HelloDelegate, this.onP_HelloCompletedDelegate, userState);
        }
    }
}
