//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosePacket.Proxy
{
    using System;
    
    
    public class AuthProxy
    {
        
        private static string _serviceUrl = "Services/Auth.svc";
        
        private static string _P_CHECK_SERVER_STATE = "server_check";
        
        private static string _P_PUBLISH_KEY = "PUBLISHKEY";
        
        private static string _P_E_TOKEN_REFRESH = "TokenRefresh";
        
        private static string _P_E_CHECK_OAUTH_VALID = "CheckVaildOAuthUser";
        
        private static string _P_E_LOGIN = "Login";
        
        private static string _P_E_GUEST_LOGIN = "GuestLogin";
        
        // Service base url
        public static string ServiceUrl
        {
            get
            {
                return _serviceUrl;
            }
        }
        
        // MethodType: GET, Segment: server_check 
        // InputType: null 
        // OutputType: null
        public static string P_CHECK_SERVER_STATE
        {
            get
            {
                return _P_CHECK_SERVER_STATE;
            }
        }
        
        // MethodType: GET, Segment: PUBLISHKEY 
        // InputType: null 
        // OutputType: null
        public static string P_PUBLISH_KEY
        {
            get
            {
                return _P_PUBLISH_KEY;
            }
        }
        
        // MethodType: GET, Segment: TokenRefresh 
        // InputType: null 
        // OutputType: PosePacket.Service.Auth.O_TokenRefresh
        public static string P_E_TOKEN_REFRESH
        {
            get
            {
                return _P_E_TOKEN_REFRESH;
            }
        }
        
        // MethodType: POST, Segment: CheckVaildOAuthUser 
        // InputType: PosePacket.Service.Auth.I_CheckVaildOAuthUser 
        // OutputType: PosePacket.Service.Auth.Models.ExternAuthUser
        public static string P_E_CHECK_OAUTH_VALID
        {
            get
            {
                return _P_E_CHECK_OAUTH_VALID;
            }
        }
        
        // MethodType: POST, Segment: Login 
        // InputType: PosePacket.Service.Auth.I_Login 
        // OutputType: PosePacket.Service.Auth.O_Login
        public static string P_E_LOGIN
        {
            get
            {
                return _P_E_LOGIN;
            }
        }
        
        // MethodType: GET, Segment: GuestLogin 
        // InputType: null 
        // OutputType: PosePacket.Service.Auth.O_Login
        public static string P_E_GUEST_LOGIN
        {
            get
            {
                return _P_E_GUEST_LOGIN;
            }
        }
    }
}
