//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosePacket.Proxy
{
    using System;
    
    
    public class AuthProxy
    {
        
        private static string _serviceUrl = "Services/Auth.svc";
        
        private static string _P_E_TokenRefresh = "TokenRefresh";
        
        private static string _P_E_CheckVaildOAuthUser = "CheckVaildOAuthUser";
        
        private static string _P_E_Login = "Login";
        
        // Service base url
        public static string ServiceUrl
        {
            get
            {
                return _serviceUrl;
            }
        }
        
        // MethodType: GET, Segment: TokenRefresh 
        // InputType: null 
        // OutputType: null
        public static string P_E_TokenRefresh
        {
            get
            {
                return _P_E_TokenRefresh;
            }
        }
        
        // MethodType: POST, Segment: CheckVaildOAuthUser 
        // InputType: PosePacket.Service.Auth.I_CheckVaildOAuthUser 
        // OutputType: PosePacket.Service.Auth.ExternAuthUser
        public static string P_E_CheckVaildOAuthUser
        {
            get
            {
                return _P_E_CheckVaildOAuthUser;
            }
        }
        
        // MethodType: POST, Segment: Login 
        // InputType: PosePacket.Service.Auth.I_Login 
        // OutputType: PosePacket.Service.Auth.O_Login
        public static string P_E_Login
        {
            get
            {
                return _P_E_Login;
            }
        }
    }
}
