//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosePacket.Proxy
{
    using System;
    
    
    public class BillingProxy
    {
        
        private static string _serviceUrl = "Services/Billing.svc";
        
        private static string _P_E_INSERT_IN_APP_BILLING_BY_GOOGLE = "InsertInAppBillingByGoogle";
        
        private static string _P_E_UPDATE_IN_APP_BILLING_BY_GOOGLE = "UpdateInAppBillingByGoogle";
        
        private static string _P_E_CHECK_MEMBERSHIP_BY_GOOGLE = "CheckMembershipByGoogle";
        
        // Service base url
        public static string ServiceUrl
        {
            get
            {
                return _serviceUrl;
            }
        }
        
        // MethodType: POST, Segment: InsertInAppBillingByGoogle 
        // InputType: PosePacket.Service.Billing.I_E_INSERT_IN_APP_BILLING_BY_GOOGLE 
        // OutputType: PosePacket.Service.Billing.O_E_INSERT_IN_APP_BILLING_BY_GOOGLE
        public static string P_E_INSERT_IN_APP_BILLING_BY_GOOGLE
        {
            get
            {
                return _P_E_INSERT_IN_APP_BILLING_BY_GOOGLE;
            }
        }
        
        // MethodType: POST, Segment: UpdateInAppBillingByGoogle 
        // InputType: PosePacket.Service.Billing.I_E_UPDATE_IN_APP_BILLING_BY_GOOGLE 
        // OutputType: PosePacket.Service.Billing.O_E_UPDATE_IN_APP_BILLING_BY_GOOGLE
        public static string P_E_UPDATE_IN_APP_BILLING_BY_GOOGLE
        {
            get
            {
                return _P_E_UPDATE_IN_APP_BILLING_BY_GOOGLE;
            }
        }
        
        // MethodType: POST, Segment: CheckMembershipByGoogle 
        // InputType: PosePacket.Service.Billing.I_E_CHECK_MEMBERSHIP_BY_GOOGLE 
        // OutputType: PosePacket.Service.Billing.O_E_CHECK_MEMBERSHIP_BY_GOOGLE
        public static string P_E_CHECK_MEMBERSHIP_BY_GOOGLE
        {
            get
            {
                return _P_E_CHECK_MEMBERSHIP_BY_GOOGLE;
            }
        }
    }
}
