// <auto-generated />
namespace Repository.Mysql.PoseGlobalDBMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class InitUserBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitUserBase));
        
        string IMigrationMetadata.Id
        {
            get { return "202003022333493_InitUserBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
