//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoseSportsPredict.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizeString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizeString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoseSportsPredict.Resources.LocalizeString", typeof(LocalizeString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add away team.
        /// </summary>
        public static string Add_Away_Team {
            get {
                return ResourceManager.GetString("Add_Away_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add home team.
        /// </summary>
        public static string Add_Home_Team {
            get {
                return ResourceManager.GetString("Add_Home_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add league.
        /// </summary>
        public static string Add_League {
            get {
                return ResourceManager.GetString("Add_League", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add match.
        /// </summary>
        public static string Add_Match {
            get {
                return ResourceManager.GetString("Add_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Matches.
        /// </summary>
        public static string All_Matches {
            get {
                return ResourceManager.GetString("All_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a product you already own..
        /// </summary>
        public static string Already_Owned_Purchase {
            get {
                return ResourceManager.GetString("Already_Owned_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poseidon Picks.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying.
        /// </summary>
        public static string Applying {
            get {
                return ResourceManager.GetString("Applying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        public static string Away {
            get {
                return ResourceManager.GetString("Away", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits.
        /// </summary>
        public static string Benefits {
            get {
                return ResourceManager.GetString("Benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmaker.
        /// </summary>
        public static string Bookmaker {
            get {
                return ResourceManager.GetString("Bookmaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bookmarks are full..
        /// </summary>
        public static string Bookmark_Inventory_Full {
            get {
                return ResourceManager.GetString("Bookmark_Inventory_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark Management.
        /// </summary>
        public static string Bookmark_Management {
            get {
                return ResourceManager.GetString("Bookmark_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark modification has been completed..
        /// </summary>
        public static string Bookmark_Modification_Completed {
            get {
                return ResourceManager.GetString("Bookmark_Modification_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Teams To Score.
        /// </summary>
        public static string Both_To_Score {
            get {
                return ResourceManager.GetString("Both_To_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Teams To Score - No.
        /// </summary>
        public static string Both_To_Score_No {
            get {
                return ResourceManager.GetString("Both_To_Score_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both Teams To Score - Yes.
        /// </summary>
        public static string Both_To_Score_Yes {
            get {
                return ResourceManager.GetString("Both_To_Score_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alarm has been canceled..
        /// </summary>
        public static string Cancle_Alarm {
            get {
                return ResourceManager.GetString("Cancle_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string Check_For_Updates {
            get {
                return ResourceManager.GetString("Check_For_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection..
        /// </summary>
        public static string Check_Internet_Connection {
            get {
                return ResourceManager.GetString("Check_Internet_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all leagues.
        /// </summary>
        public static string Collapse_All_Leagues {
            get {
                return ResourceManager.GetString("Collapse_All_Leagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all matches.
        /// </summary>
        public static string Collapse_All_Matches {
            get {
                return ResourceManager.GetString("Collapse_All_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete away team.
        /// </summary>
        public static string Delete_Away_Team {
            get {
                return ResourceManager.GetString("Delete_Away_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark have been deleted..
        /// </summary>
        public static string Delete_Bookmark {
            get {
                return ResourceManager.GetString("Delete_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete home team.
        /// </summary>
        public static string Delete_Home_Team {
            get {
                return ResourceManager.GetString("Delete_Home_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete league.
        /// </summary>
        public static string Delete_League {
            get {
                return ResourceManager.GetString("Delete_League", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete match.
        /// </summary>
        public static string Delete_Match {
            get {
                return ResourceManager.GetString("Delete_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond.
        /// </summary>
        public static string Diamond {
            get {
                return ResourceManager.GetString("Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View prediction data without video ad for 7 days.
        /// </summary>
        public static string Diamond_Advantage_1 {
            get {
                return ResourceManager.GetString("Diamond_Advantage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded to 50 bookmarked matches.
        /// </summary>
        public static string Diamond_Advantage_2 {
            get {
                return ResourceManager.GetString("Diamond_Advantage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded to 30 bookmarked leagues.
        /// </summary>
        public static string Diamond_Advantage_3 {
            get {
                return ResourceManager.GetString("Diamond_Advantage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded to 30 bookmarked teams.
        /// </summary>
        public static string Diamond_Advantage_4 {
            get {
                return ResourceManager.GetString("Diamond_Advantage_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot&apos;t show again.
        /// </summary>
        public static string Dont_Show_Again {
            get {
                return ResourceManager.GetString("Dont_Show_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        public static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        public static string Draw_Initial {
            get {
                return ResourceManager.GetString("Draw_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Bookmarks.
        /// </summary>
        public static string Edit_Bookmark {
            get {
                return ResourceManager.GetString("Edit_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new app update..
        /// </summary>
        public static string Exist_App_Update {
            get {
                return ResourceManager.GetString("Exist_App_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all leagues.
        /// </summary>
        public static string Expand_All_Leagues {
            get {
                return ResourceManager.GetString("Expand_All_Leagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all matches.
        /// </summary>
        public static string Expand_All_Matches {
            get {
                return ResourceManager.GetString("Expand_All_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        public static string Expiration_Date {
            get {
                return ResourceManager.GetString("Expiration_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store cannot be accessed..
        /// </summary>
        public static string Fail_Store_Connect {
            get {
                return ResourceManager.GetString("Fail_Store_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite leagues.
        /// </summary>
        public static string Favorite_Leagues {
            get {
                return ResourceManager.GetString("Favorite_Leagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite teams.
        /// </summary>
        public static string Favorite_Teams {
            get {
                return ResourceManager.GetString("Favorite_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Score.
        /// </summary>
        public static string Final_Score {
            get {
                return ResourceManager.GetString("Final_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fined Matches.
        /// </summary>
        public static string Finished_Matches {
            get {
                return ResourceManager.GetString("Finished_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football.
        /// </summary>
        public static string Football {
            get {
                return ResourceManager.GetString("Football", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content is for VIP members..
        /// </summary>
        public static string For_VIP_User {
            get {
                return ResourceManager.GetString("For_VIP_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Against.
        /// </summary>
        public static string Goal_Against {
            get {
                return ResourceManager.GetString("Goal_Against", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal For.
        /// </summary>
        public static string Goal_For {
            get {
                return ResourceManager.GetString("Goal_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal For/Against.
        /// </summary>
        public static string Goal_For_Against_Avg {
            get {
                return ResourceManager.GetString("Goal_For_Against_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Statistics.
        /// </summary>
        public static string Goal_Statistics {
            get {
                return ResourceManager.GetString("Goal_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H/A Goal Against.
        /// </summary>
        public static string H_A_Goal_Against {
            get {
                return ResourceManager.GetString("H_A_Goal_Against", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H/A Goal For.
        /// </summary>
        public static string H_A_Goal_For {
            get {
                return ResourceManager.GetString("H_A_Goal_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2H.
        /// </summary>
        public static string H2H {
            get {
                return ResourceManager.GetString("H2H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last login.
        /// </summary>
        public static string Last_Login {
            get {
                return ResourceManager.GetString("Last_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League.
        /// </summary>
        public static string League {
            get {
                return ResourceManager.GetString("League", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string League_Points {
            get {
                return ResourceManager.GetString("League_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leagues.
        /// </summary>
        public static string Leagues {
            get {
                return ResourceManager.GetString("Leagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Facebook.
        /// </summary>
        public static string Login_With_Facebook {
            get {
                return ResourceManager.GetString("Login_With_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Google.
        /// </summary>
        public static string Login_With_Google {
            get {
                return ResourceManager.GetString("Login_With_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login....
        /// </summary>
        public static string Loginning {
            get {
                return ResourceManager.GetString("Loginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lose.
        /// </summary>
        public static string Lose {
            get {
                return ResourceManager.GetString("Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string Lose_Initial {
            get {
                return ResourceManager.GetString("Lose_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match will begin soon..
        /// </summary>
        public static string Match_Begin_Soon {
            get {
                return ResourceManager.GetString("Match_Begin_Soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My matches.
        /// </summary>
        public static string Match_Filter_By_Bookmark {
            get {
                return ResourceManager.GetString("Match_Filter_By_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Match_Finished {
            get {
                return ResourceManager.GetString("Match_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not start.
        /// </summary>
        public static string Match_Not_Start {
            get {
                return ResourceManager.GetString("Match_Not_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing.
        /// </summary>
        public static string Match_Ongoing {
            get {
                return ResourceManager.GetString("Match_Ongoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by league.
        /// </summary>
        public static string Match_Sort_By_League {
            get {
                return ResourceManager.GetString("Match_Sort_By_League", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Time.
        /// </summary>
        public static string Match_Sort_By_Time {
            get {
                return ResourceManager.GetString("Match_Sort_By_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Winner.
        /// </summary>
        public static string Match_Winner {
            get {
                return ResourceManager.GetString("Match_Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home - Lose.
        /// </summary>
        public static string Match_Winner_Lose {
            get {
                return ResourceManager.GetString("Match_Winner_Lose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home- Draw or Lose.
        /// </summary>
        public static string Match_Winner_Lose_Or_Draw {
            get {
                return ResourceManager.GetString("Match_Winner_Lose_Or_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home - Win.
        /// </summary>
        public static string Match_Winner_Win {
            get {
                return ResourceManager.GetString("Match_Winner_Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home - Win or Draw.
        /// </summary>
        public static string Match_Winner_Win_Or_Draw {
            get {
                return ResourceManager.GetString("Match_Winner_Win_Or_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mo.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string My_Profile {
            get {
                return ResourceManager.GetString("My_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no bookmarked leagues..
        /// </summary>
        public static string No_Bookmarked_Leagues {
            get {
                return ResourceManager.GetString("No_Bookmarked_Leagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no bookmarked Matches..
        /// </summary>
        public static string No_Bookmarked_Matches {
            get {
                return ResourceManager.GetString("No_Bookmarked_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no bookmarked Teams..
        /// </summary>
        public static string No_Bookmarked_Teams {
            get {
                return ResourceManager.GetString("No_Bookmarked_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no data available..
        /// </summary>
        public static string No_Data_Available {
            get {
                return ResourceManager.GetString("No_Data_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no matches..
        /// </summary>
        public static string No_Match_datas {
            get {
                return ResourceManager.GetString("No_Match_datas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results found..
        /// </summary>
        public static string No_Search_Results {
            get {
                return ResourceManager.GetString("No_Search_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authenticated User..
        /// </summary>
        public static string Not_Authenticated_Credencials {
            get {
                return ResourceManager.GetString("Not_Authenticated_Credencials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not enough data to predict..
        /// </summary>
        public static string Not_Enough_Data_Predict {
            get {
                return ResourceManager.GetString("Not_Enough_Data_Predict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string Occur_Error {
            get {
                return ResourceManager.GetString("Occur_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odds.
        /// </summary>
        public static string Odds {
            get {
                return ResourceManager.GetString("Odds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing matches.
        /// </summary>
        public static string Ongoing_matches {
            get {
                return ResourceManager.GetString("Ongoing_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        public static string Over {
            get {
                return ResourceManager.GetString("Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5 Goal Over.
        /// </summary>
        public static string Over_1_5 {
            get {
                return ResourceManager.GetString("Over_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5 Goal Over.
        /// </summary>
        public static string Over_2_5 {
            get {
                return ResourceManager.GetString("Over_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.5 Goal Over.
        /// </summary>
        public static string Over_3_5 {
            get {
                return ResourceManager.GetString("Over_3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.5 Goal Over.
        /// </summary>
        public static string Over_4_5 {
            get {
                return ResourceManager.GetString("Over_4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participating Leagues.
        /// </summary>
        public static string Participating_Leagues {
            get {
                return ResourceManager.GetString("Participating_Leagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participating Teams.
        /// </summary>
        public static string Participating_Teams {
            get {
                return ResourceManager.GetString("Participating_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment has been pending. Please check your payment..
        /// </summary>
        public static string Payment_Pending_Please_Check {
            get {
                return ResourceManager.GetString("Payment_Pending_Please_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string Played_Initial {
            get {
                return ResourceManager.GetString("Played_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pts.
        /// </summary>
        public static string Points_Initial {
            get {
                return ResourceManager.GetString("Points_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted Picks.
        /// </summary>
        public static string Predicted_Picks {
            get {
                return ResourceManager.GetString("Predicted_Picks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictions.
        /// </summary>
        public static string Predictions {
            get {
                return ResourceManager.GetString("Predictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click &apos;BACK&apos; again to exit..
        /// </summary>
        public static string PressBack_Twice_To_Exit {
            get {
                return ResourceManager.GetString("PressBack_Twice_To_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are paid products that are not consumed..
        /// </summary>
        public static string Product_Not_Consumed {
            get {
                return ResourceManager.GetString("Product_Not_Consumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP Lounge daily recommended matches provided.
        /// </summary>
        public static string Provide_VIP_Picks {
            get {
                return ResourceManager.GetString("Provide_VIP_Picks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Form.
        /// </summary>
        public static string Recent_Form {
            get {
                return ResourceManager.GetString("Recent_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Record.
        /// </summary>
        public static string Recent_Record {
            get {
                return ResourceManager.GetString("Recent_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent search.
        /// </summary>
        public static string Recent_Search {
            get {
                return ResourceManager.GetString("Recent_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Matches.
        /// </summary>
        public static string Recommended_Matches {
            get {
                return ResourceManager.GetString("Recommended_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Remember_Account {
            get {
                return ResourceManager.GetString("Remember_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove video ads.
        /// </summary>
        public static string Remove_Video_Ads {
            get {
                return ResourceManager.GetString("Remove_Video_Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is required..
        /// </summary>
        public static string Require_Login {
            get {
                return ResourceManager.GetString("Require_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest Period.
        /// </summary>
        public static string Rest_Period {
            get {
                return ResourceManager.GetString("Rest_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sched Matches.
        /// </summary>
        public static string Scheduled_Matches {
            get {
                return ResourceManager.GetString("Scheduled_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search bookmark....
        /// </summary>
        public static string Search_Bookmark {
            get {
                return ResourceManager.GetString("Search_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Country, League....
        /// </summary>
        public static string Search_League_Country {
            get {
                return ResourceManager.GetString("Search_League_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string Search_Results {
            get {
                return ResourceManager.GetString("Search_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season End.
        /// </summary>
        public static string Season_EndDate {
            get {
                return ResourceManager.GetString("Season_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season Start.
        /// </summary>
        public static string Season_StartDate {
            get {
                return ResourceManager.GetString("Season_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a filter.
        /// </summary>
        public static string Select_Filter {
            get {
                return ResourceManager.GetString("Select_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Interface Language.
        /// </summary>
        public static string Select_Interface_Language {
            get {
                return ResourceManager.GetString("Select_Interface_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not available..
        /// </summary>
        public static string Service_Not_Available {
            get {
                return ResourceManager.GetString("Service_Not_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alarm has been set..
        /// </summary>
        public static string Set_Alarm {
            get {
                return ResourceManager.GetString("Set_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s been saved in the bookmark..
        /// </summary>
        public static string Set_Bookmark {
            get {
                return ResourceManager.GetString("Set_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share app.
        /// </summary>
        public static string Share_App {
            get {
                return ResourceManager.GetString("Share_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standings.
        /// </summary>
        public static string Standings {
            get {
                return ResourceManager.GetString("Standings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purchase was successful, but an error occurred on the server..
        /// </summary>
        public static string Success_Purchase_But_Server_Error {
            get {
                return ResourceManager.GetString("Success_Purchase_But_Server_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested.
        /// </summary>
        public static string Suggested_Leagues {
            get {
                return ResourceManager.GetString("Suggested_Leagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under.
        /// </summary>
        public static string Under {
            get {
                return ResourceManager.GetString("Under", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5 Goal Under.
        /// </summary>
        public static string Under_1_5 {
            get {
                return ResourceManager.GetString("Under_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5 Goal Under.
        /// </summary>
        public static string Under_2_5 {
            get {
                return ResourceManager.GetString("Under_2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.5 Goal Under.
        /// </summary>
        public static string Under_3_5 {
            get {
                return ResourceManager.GetString("Under_3_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.5 Goal Under.
        /// </summary>
        public static string Under_4_5 {
            get {
                return ResourceManager.GetString("Under_4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Over.
        /// </summary>
        public static string Under_Over {
            get {
                return ResourceManager.GetString("Under_Over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        public static string Unknown_Error {
            get {
                return ResourceManager.GetString("Unknown_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string Unlock {
            get {
                return ResourceManager.GetString("Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked.
        /// </summary>
        public static string Unlocked {
            get {
                return ResourceManager.GetString("Unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All prediction data is released for 5 minutes..
        /// </summary>
        public static string Unlocked_Prediction_Five_Minutes {
            get {
                return ResourceManager.GetString("Unlocked_Prediction_Five_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member No.
        /// </summary>
        public static string User_No {
            get {
                return ResourceManager.GetString("User_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem loading the ad..
        /// </summary>
        public static string VidonAd_Load_Fail {
            get {
                return ResourceManager.GetString("VidonAd_Load_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View form.
        /// </summary>
        public static string View_Form {
            get {
                return ResourceManager.GetString("View_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP.
        /// </summary>
        public static string VIP {
            get {
                return ResourceManager.GetString("VIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View prediction data without video ad for one month.
        /// </summary>
        public static string VIP_Advantage_1 {
            get {
                return ResourceManager.GetString("VIP_Advantage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded to 100 bookmarked matches.
        /// </summary>
        public static string VIP_Advantage_2 {
            get {
                return ResourceManager.GetString("VIP_Advantage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited number of bookmarked leagues.
        /// </summary>
        public static string VIP_Advantage_3 {
            get {
                return ResourceManager.GetString("VIP_Advantage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlimited number of bookmarked teams.
        /// </summary>
        public static string VIP_Advantage_4 {
            get {
                return ResourceManager.GetString("VIP_Advantage_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete banner ad at the bottom of the page.
        /// </summary>
        public static string VIP_Advantage_5 {
            get {
                return ResourceManager.GetString("VIP_Advantage_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP Lounge.
        /// </summary>
        public static string VIP_Lounge {
            get {
                return ResourceManager.GetString("VIP_Lounge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to logout?.
        /// </summary>
        public static string Want_Logout {
            get {
                return ResourceManager.GetString("Want_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome !.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        public static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string Win_Initial {
            get {
                return ResourceManager.GetString("Win_Initial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a review.
        /// </summary>
        public static string Write_Review {
            get {
                return ResourceManager.GetString("Write_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
