//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoseSportsPredict.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizeString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizeString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoseSportsPredict.Resources.LocalizeString", typeof(LocalizeString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Delete a match alarm.
        /// </summary>
        public static string Add_Delete_Matches_Alarm {
            get {
                return ResourceManager.GetString("Add_Delete_Matches_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying.
        /// </summary>
        public static string Applying {
            get {
                return ResourceManager.GetString("Applying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alarm has been canceled..
        /// </summary>
        public static string Cancle_Alarm {
            get {
                return ResourceManager.GetString("Cancle_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your internet connection..
        /// </summary>
        public static string Check_Internet_Connection {
            get {
                return ResourceManager.GetString("Check_Internet_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all leagues.
        /// </summary>
        public static string Collapse_All_Leagues {
            get {
                return ResourceManager.GetString("Collapse_All_Leagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark have been deleted..
        /// </summary>
        public static string Delete_Bookmark {
            get {
                return ResourceManager.GetString("Delete_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all leagues.
        /// </summary>
        public static string Expand_All_Leagues {
            get {
                return ResourceManager.GetString("Expand_All_Leagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Matches.
        /// </summary>
        public static string Finished_Matches {
            get {
                return ResourceManager.GetString("Finished_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football.
        /// </summary>
        public static string Football {
            get {
                return ResourceManager.GetString("Football", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2H.
        /// </summary>
        public static string H2H {
            get {
                return ResourceManager.GetString("H2H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leagues.
        /// </summary>
        public static string Leagues {
            get {
                return ResourceManager.GetString("Leagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login....
        /// </summary>
        public static string Loginning {
            get {
                return ResourceManager.GetString("Loginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match will begin soon..
        /// </summary>
        public static string Match_Begin_Soon {
            get {
                return ResourceManager.GetString("Match_Begin_Soon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My matches.
        /// </summary>
        public static string Match_Filter_By_Bookmark {
            get {
                return ResourceManager.GetString("Match_Filter_By_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Match_Finished {
            get {
                return ResourceManager.GetString("Match_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not start.
        /// </summary>
        public static string Match_Not_Start {
            get {
                return ResourceManager.GetString("Match_Not_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing.
        /// </summary>
        public static string Match_Ongoing {
            get {
                return ResourceManager.GetString("Match_Ongoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by league.
        /// </summary>
        public static string Match_Sort_By_League {
            get {
                return ResourceManager.GetString("Match_Sort_By_League", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Time.
        /// </summary>
        public static string Match_Sort_By_Time {
            get {
                return ResourceManager.GetString("Match_Sort_By_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        public static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches Filtering.
        /// </summary>
        public static string Matches_Filtering {
            get {
                return ResourceManager.GetString("Matches_Filtering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no bookmarked leagues..
        /// </summary>
        public static string No_Bookmarked_Leagues {
            get {
                return ResourceManager.GetString("No_Bookmarked_Leagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no bookmarked Matches..
        /// </summary>
        public static string No_Bookmarked_Matches {
            get {
                return ResourceManager.GetString("No_Bookmarked_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no bookmarked Teams..
        /// </summary>
        public static string No_Bookmarked_Teams {
            get {
                return ResourceManager.GetString("No_Bookmarked_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches were predicted..
        /// </summary>
        public static string No_Match_datas {
            get {
                return ResourceManager.GetString("No_Match_datas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No search results found..
        /// </summary>
        public static string No_Search_Results {
            get {
                return ResourceManager.GetString("No_Search_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authenticated User..
        /// </summary>
        public static string Not_Authenticated_Credencials {
            get {
                return ResourceManager.GetString("Not_Authenticated_Credencials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred..
        /// </summary>
        public static string Occur_Error {
            get {
                return ResourceManager.GetString("Occur_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odds.
        /// </summary>
        public static string Odds {
            get {
                return ResourceManager.GetString("Odds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing matches.
        /// </summary>
        public static string Ongoing_matches {
            get {
                return ResourceManager.GetString("Ongoing_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictions.
        /// </summary>
        public static string Predictions {
            get {
                return ResourceManager.GetString("Predictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click &apos;BACK&apos; again to exit..
        /// </summary>
        public static string PressBack_Twice_To_Exit {
            get {
                return ResourceManager.GetString("PressBack_Twice_To_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Matches.
        /// </summary>
        public static string Scheduled_Matches {
            get {
                return ResourceManager.GetString("Scheduled_Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Country, League....
        /// </summary>
        public static string Search_League_Country {
            get {
                return ResourceManager.GetString("Search_League_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service is not available..
        /// </summary>
        public static string Service_Not_Available {
            get {
                return ResourceManager.GetString("Service_Not_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alarm has been set..
        /// </summary>
        public static string Set_Alarm {
            get {
                return ResourceManager.GetString("Set_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s been saved in the bookmark..
        /// </summary>
        public static string Set_Bookmark {
            get {
                return ResourceManager.GetString("Set_Bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standings.
        /// </summary>
        public static string Standings {
            get {
                return ResourceManager.GetString("Standings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome !.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
