//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosePacket.Proxy
{
    using System;
    
    
    public class HelloWorldProxy
    {
        
        private static string _serviceUrl = "Service/HelloWorld.svc";
        
        private static string _P_Hello = "Hello";
        
        // Service base url
        public static string ServiceUrl
        {
            get
            {
                return _serviceUrl;
            }
        }
        
        // MethodType: POST, Segment: Hello 
        // InputType: PosePacket.Service.HelloWorld.I_Hello 
        // OutputType: PosePacket.Service.HelloWorld.O_Hello
        public static string P_Hello
        {
            get
            {
                return _P_Hello;
            }
        }
    }
}
